name: .NET Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./ViolastroBot/ViolastroBot.csproj

      - name: Build
        run: dotnet build ./ViolastroBot/ViolastroBot.csproj --no-restore --configuration Release

      - name: Publish as Executable
        run: dotnet publish ./ViolastroBot/ViolastroBot.csproj -r win-x64 --no-build --configuration Release --output ./publish /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

      - name: Archive Executable
        run: Compress-Archive -Path ./publish/* -DestinationPath ./ViolastroBot.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ViolastroBot.zip
          asset_name: ViolastroBot.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
