name: .NET Build, Test, Publish and Release

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.0.x'
  RUNTIME: 'win-x64'

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ./ViolastroBot/ViolastroBot.csproj --runtime ${{ env.RUNTIME }}

    - name: Build
      run: dotnet build ./ViolastroBot/ViolastroBot.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test ./ViolastroBot.Tests/ViolastroBot.Tests.csproj --no-build --configuration Release --verbosity normal

    - name: Publish as Executable
      run: dotnet publish ./ViolastroBot/ViolastroBot.csproj -r ${{ env.RUNTIME }} --no-build --configuration Release --output ./publish /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    - name: Zip the publish output
      run: Compress-Archive -Path ./publish/* -DestinationPath ./ViolastroBot.zip

    - name: Create Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ViolastroBot.zip
        asset_name: ViolastroBot.zip
        asset_content_type: application/zip
